//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENTS
    {
        public int ID { get; set; }
        public Nullable<int> CONTENTID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> USERID { get; set; }
    
        public virtual CONTENTS CONTENTS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
