//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTENTS()
        {
            this.COMMENTS = new HashSet<COMMENTS>();
            this.CONTENTFILES = new HashSet<CONTENTFILES>();
        }
    
        public int ID { get; set; }
        public string HEAD { get; set; }
        public string CONTENTTEXT { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public int STATUS { get; set; }
        public int USERID { get; set; }
        public int CATEGORIID { get; set; }
    
        public virtual CATEGORİ CATEGORİ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTS> COMMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTENTFILES> CONTENTFILES { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
